apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mon
  namespace: monitoring
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 9.1.0
